# Site settings
title: Louis Lefevre
description: Personal portfolio and blog
lang: en-GB
timezone: Europe/London
image: assets/img/ogp.png # Image used for Open Graph (https://ogp.me/)
repo: https://github.com/louislefevre/louislefevre.github.io
mode: dark

# Profile settings
author:
  name: Louis Lefevre
  bio: UCL Software Systems Engineering MSc Graduate
  username: louislefevre
  github: louislefevre
  email: louislefev@gmail.com
  avatar: /assets/img/avatar.jpg

# URL settings
url: "https://louislefevre.github.io/"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
sass:
  style: compressed

# Include in conversion
include:
  - _redirects
  - .htaccess

# Exclude in conversion
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
